### ISSUE TITLE
Add Otsu thresholding

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#10]
https://en.m.wikipedia.org/wiki/Otsu%27s_method

**Comment by akonneker** [comment]
So I'm adding histogram, threshold, threshold_mut, and otsu_level functions.

As it is, the otsu method will return the optimal threshold, which you would then apply with the threshold function.

I ran into an issue when compiling things however. This is the first time I'm used the image crate, so when I went to compile my code, I got an error during the compilation of the custom_derive-0.1.2 crate. Do I need to be running the nightly or anything?

**Comment by theotherphil** [comment]
Yes, this only compiles on nightly. As far as I know, the #[bench] attribute still requires nightly, and since switching I've not paid any attention to any other crates that might also need it.

There's already a cumulative_histogram function in contrast.rs, so you might want to separate the "cumulative" and "histogram" parts of that and use/replace the latter in/with your new code. It's only a couple of lines, but we might as well use a common implementation.

**Comment by akonneker** [comment]
I apologize for letting this sit. I've been pretty swamped lately. I'll finish writing tests and send out a PR tomorrow.

**Comment by theotherphil** [comment]
No worries, thanks!

**Comment by akonneker** [comment]
Okay, apparently I was still being wildly optimistic about my schedule. I finally finished the last function yesterday, though. Woo-hoo! 

I'd like to ask your thoughts on a minor implementation detail, however.  According to wikipedia/the matlab implementation, the otsu method usually returns a real value on the interval [0,1].

As I've written it, however, I just return a value that's the type of the input image (which for now is assumed to be u8, like everything else in contrast.rs).

Is there any merit in following convention? For my 2 cents, I think it makes more sense to return a value that matches the pixels in the image, otherwise you'd need to convert it to do any comparisons.

**Comment by theotherphil** [comment]
I agree that it should return a threshold that can be used directly, rather than scaling to [0, 1] just to reverse the scaling whenever you use the value.
