### ISSUE TITLE
Support non-square kernels in median_filter

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#250]

**Comment by TH3CHARLie** [comment]
I implement a draft version on this, check https://github.com/TH3CHARLie/imageproc/commit/820d87e78984f71e6e55f9d7ec8bdae6bf0b9de4. I referenced the API design of `box_filter` and implemented here.

There are several things I know that are missing or needing further discussion:

- Documents: The docs are unchanged since I am not sure the changes I made will be accepted or not
- Even size kernels: Current implementation only supports kernels that are odd length on each axis. Should we support even size kernels?

**Comment by theotherphil** [comment]
Looks good to me (although I'm not sure why you've removed the comment from the reference implementation of median filter). I don't remember the reason for not supporting even size kernels.

**Comment by TH3CHARLie** [comment]
I am not quite sure what's the removed comment you mentioned since I haven't seen any at the diff. 

As for the even size kernels, I did some quick search and find that current OpenCV implementation limits the median filter kernels to be odd sizes. I assume that maybe not many cases that you need to use an even size kernel in a median filter. But I do think it is better to support a more generalized version of image filter like `filter2d` that takes arbitrary rectangle kernels.

**Comment by theotherphil** [comment]
I'd be fine with merging a PR to support the more general case if it wasn't massively more complicated and didn't make the currently supported cases slower.

**Comment by TH3CHARLie** [comment]
> I'd be fine with merging a PR to support the more general case if it wasn't massively more complicated and didn't make the currently supported cases slower.

The more general case, at this point, can be implemented independently without affecting any existing filters. It does not need to be used to refactor the implementations of current filters, but it could be if performance permits.

Back to the current topic, is there anything you may come up with that are missing in the median filter, maybe I can fix them quick

**Comment by theotherphil** [comment]
I'm not totally clear what your question means. If you're asking about your changes specifically then apart from updating the docs they look fine to me.

**Comment by TH3CHARLie** [comment]
> I'm not totally clear what your question means. If you're asking about your changes specifically then apart from updating the docs they look fine to me.

OK I will update the docs with the latest changes

**Comment by TH3CHARLie** [comment]
#319 I open a new PR, please check it out.

**Comment by theotherphil** [comment]
Fixed by #319
